### ISSUE TITLE
oc

### ISSUE THREAD

**Issue by liuzy88** [Lyrance/ASUS-Prime-Z390M-PLUS-EFI#1]
我的OC版本OK了,一切正常
欢迎指正 ^_^
https://github.com/liuzy88/PRIME-Z390M-PLUS-9700K-5700XT-OPENCORE

**Comment by Lyrance** [comment]
因为我的主板需要HDMI输出信号，所以只能用10.15.4及以下的版本。oc我尝试过有点麻烦，现在还在发展阶段各项驱动适配有点不行我就没再用

**Comment by Lyrance** [comment]
好的谢谢你
